/* Tinkercad Skills Check — Question Bank
   WNS Studio | 54 questions covering core Tinkercad 3D Design skills.
   Each test draws 20 random questions from this bank (see app.js).
   type: "tf" (true/false) or "mc" (multiple choice)
   img (optional): filename in /images/ folder, shown above the question
*/

const QUESTION_BANK = [
  { id: 1, type: "tf", text: "Tinkercad is completely free to use for students.", answer: true },
  { id: 2, type: "tf", text: "Tinkercad runs inside a web browser, so you don't need to install any special software to use it.", answer: true },
  { id: 3, type: "mc", text: "Which company makes Tinkercad?", options: ["Adobe", "Autodesk", "Microsoft", "Google"], answer: 1 },
  { id: 4, type: "tf", text: "You need an internet connection to open and edit your designs in Tinkercad.", answer: true },
  { id: 5, type: "mc", img: "shapes-panel.png", text: "In this screenshot, where do you drag a shape from to add it to your design?", options: ["The flat grid area on the left", "The panel of shape icons on the right", "The Import button at the top", "The ruler icon"], answer: 1 },
  { id: 6, type: "mc", text: "The flat grid where you build your 3D design in Tinkercad is called the ____.", options: ["baseplate", "workplane", "canvas", "stage"], answer: 1 },
  { id: 7, type: "tf", text: "Basic Shapes in Tinkercad include boxes, cylinders, cones, and spheres.", answer: true },
  { id: 8, type: "mc", img: "primitive-shapes.png", text: "Based on the picture, a cylinder with a hole running through the middle (like a pipe) is called a ____ in Tinkercad's shape panel.", options: ["Tube", "Torus", "Cylinder", "Sphere"], answer: 0 },
  { id: 9, type: "tf", text: "Every shape in Tinkercad is set to be either a \"Solid\" or a \"Hole.\"", answer: true },
  { id: 10, type: "mc", img: "creating-holes.png", text: "In this picture, the see-through orange shape overlapping the wrench is being used to ____.", options: ["Add color to the wrench", "Cut a hole into the wrench", "Measure the wrench", "Copy the wrench"], answer: 1 },
  { id: 11, type: "tf", text: "A Hole shape only cuts away material once it is grouped together with a Solid shape.", answer: true },
  { id: 12, type: "mc", text: "Which action turns a Solid and a Hole shape into one finished object with a cut-out?", options: ["Align", "Group", "Duplicate", "Mirror"], answer: 1 },
  { id: 13, type: "tf", text: "Once two shapes are grouped, you can still ungroup them later to edit the pieces separately.", answer: true },
  { id: 14, type: "mc", img: "group-hole.png", text: "Looking at the picture, what will happen when the plain red box and the box with a hole in the top are grouped together?", options: ["They merge into one solid box with no hole", "The hole punches through wherever it overlaps the box", "Both shapes disappear", "The colors blend together"], answer: 1 },
  { id: 15, type: "tf", text: "For a hole to cut all the way through a solid shape, the hole shape must be taller (or longer) than the solid it is cutting.", answer: true },
  { id: 16, type: "mc", img: "move-tool.png", text: "In this picture, what do the light blue arrows let you do to the red cube?", options: ["Change its color", "Move it across the workplane", "Delete it", "Rotate it"], answer: 1 },
  { id: 17, type: "tf", text: "Besides sliding a shape across the workplane, Tinkercad's Move tool also lets you lift a shape straight up into the air.", answer: true },
  { id: 18, type: "mc", img: "rotate-tool.png", text: "What are the curved arrows shown next to each cube used for?", options: ["Rotating the shape", "Scaling the shape", "Duplicating the shape", "Changing the shape's color"], answer: 0 },
  { id: 19, type: "tf", text: "You can rotate a shape around any of the three axes, not just spin it flat on the workplane.", answer: true },
  { id: 20, type: "mc", img: "scale-tool.png", text: "In the picture, dragging the white handles on the corners and edges of the selected box lets you ____.", options: ["Move the shape", "Resize (scale) the shape", "Change its color", "Group it with another shape"], answer: 1 },
  { id: 21, type: "tf", text: "Dragging a corner handle to scale a shape resizes it in all directions at once, while dragging a handle on a flat face resizes only one dimension.", answer: true },
  { id: 22, type: "mc", text: "Besides dragging handles, what is another way to set a shape's exact length, width, and height in Tinkercad?", options: ["Right-click and choose \"Exact Size\"", "Type numbers directly into the shape's size boxes", "You cannot set an exact size", "Use the Export menu"], answer: 1 },
  { id: 23, type: "mc", img: "view-cube.png", text: "What is this \"TOP / FRONT / RIGHT\" cube used for?", options: ["Choosing a shape's color", "Changing your camera view/angle of the workplane", "Measuring distances", "Exporting your design"], answer: 1 },
  { id: 24, type: "tf", text: "Clicking the Home icon resets your camera view back to the default angle.", answer: true },
  { id: 25, type: "tf", text: "Scrolling your mouse wheel while working in Tinkercad zooms your camera in and out.", answer: true },
  { id: 26, type: "mc", text: "To rotate your camera around your design (orbit), you typically ____.", options: ["Right-click and drag (or use the view cube)", "Press the spacebar", "Double-click the workplane", "Press Delete"], answer: 0 },
  { id: 27, type: "mc", img: "align-tool.png", text: "What do the small black dots that appear along the edges and center in this picture represent?", options: ["Places you can click to align the selected shapes", "Grid snap points only", "Colors you can choose", "Errors in your design"], answer: 0 },
  { id: 28, type: "tf", text: "The Align tool can center multiple shapes relative to each other, not just line them up on one edge.", answer: true },
  { id: 29, type: "mc", text: "You want three shapes to all be centered exactly on top of each other. Which tool should you use?", options: ["Ruler", "Align", "Text", "Shape Generators"], answer: 1 },
  { id: 30, type: "mc", img: "copy-tool.png", text: "In the picture, an arrow points from the original red cube to a second cube. What action does this represent?", options: ["Duplicate", "Copy and Paste", "Group", "Mirror"], answer: 1 },
  { id: 31, type: "tf", text: "In Tinkercad, Duplicate places a new copy of a shape without you needing to Copy and Paste separately.", answer: true },
  { id: 32, type: "mc", text: "If you duplicate a shape several times in a row without moving it, what usually happens?", options: ["Each copy stacks in the exact same spot", "Each copy is offset slightly so you can see there are multiple", "Tinkercad only allows one duplicate", "The shape gets bigger each time"], answer: 1 },
  { id: 33, type: "tf", text: "You can change the color of a shape by clicking its colored circle icon or right-clicking it.", answer: true },
  { id: 34, type: "mc", img: "text-shapes.png", text: "In this design, what tool was most likely used to add the word \"Hello!\" as a 3D object?", options: ["Shape Generators", "The Text tool", "The Ruler", "Align"], answer: 1 },
  { id: 35, type: "tf", text: "Besides basic 3D shapes, Tinkercad also has a gallery of shapes like stars, hearts, and animals you can drag onto the workplane.", answer: true },
  { id: 36, type: "mc", text: "What are Tinkercad's \"Shape Generators\" mainly used for?", options: ["Deleting shapes", "Creating customizable, more complex shapes (like gears or patterns)", "Changing units from mm to inches", "Logging into your account"], answer: 1 },
  { id: 37, type: "tf", text: "The Ruler tool lets you see and set exact measurements/dimensions of a shape on the workplane.", answer: true },
  { id: 38, type: "mc", text: "By default, Tinkercad measures your design in ____.", options: ["inches", "millimeters", "centimeters", "feet"], answer: 1 },
  { id: 39, type: "tf", text: "You can switch Tinkercad's measurement units between millimeters and inches.", answer: true },
  { id: 40, type: "mc", text: "The small squares on the workplane that shapes \"snap\" to when you move them are called the ____.", options: ["ruler marks", "grid", "axis lines", "baseplate lines"], answer: 1 },
  { id: 41, type: "tf", text: "You can create a new workplane directly on the face (side) of an existing 3D shape to build at an angle.", answer: true },
  { id: 42, type: "mc", text: "Which of these is NOT one of the three basic transform tools you learned about?", options: ["Move", "Rotate", "Scale", "Import"], answer: 3 },
  { id: 43, type: "tf", text: "To save your progress and share your designs in Tinkercad, you need to be logged into an account.", answer: true },
  { id: 44, type: "mc", text: "What is the most common file type used to export a Tinkercad design for 3D printing?", options: [".STL", ".MP3", ".DOCX", ".PNG"], answer: 0 },
  { id: 45, type: "tf", text: "You can import your own STL or SVG files into Tinkercad to combine with your design.", answer: true },
  { id: 48, type: "mc", text: "In the Community Gallery, what does making your own copy of a public design (sometimes called \"remixing\") let you do?", options: ["Delete someone else's design", "Make your own editable copy of a public design to modify", "Report the design", "Automatically 3D print it"], answer: 1 },
  { id: 49, type: "tf", text: "It's good etiquette to give credit to the original designer when you remix or build on someone else's public Tinkercad design.", answer: true },
  { id: 50, type: "tf", text: "Before printing any 3D design at school, it's a good idea to check with your teacher first.", answer: true },
  { id: 51, type: "mc", text: "Which of these is a good safety habit around a 3D printer?", options: ["Touch the nozzle while it's printing to see if it's warm", "Never leave a running 3D printer completely unattended for long periods without checking on it", "Print anything you want without asking", "Unplug the printer while it's mid-print to save time"], answer: 1 },
  { id: 52, type: "tf", text: "3D printing turns your digital Tinkercad design into a real, physical object, built up layer by layer.", answer: true },
  { id: 53, type: "mc", text: "If two overlapping Solid shapes (no holes involved) are Grouped together, what happens?", options: ["They combine into a single solid shape", "Nothing changes", "One shape deletes the other", "They automatically become a hole"], answer: 0 },
  { id: 54, type: "tf", text: "The Undo command can be used to fix a mistake, like an accidental move or deletion.", answer: true },
  { id: 55, type: "mc", text: "What is the common keyboard shortcut used to undo a mistake in most design programs, including Tinkercad?", options: ["Ctrl+Z (or Cmd+Z)", "Ctrl+P", "Ctrl+S", "Alt+F4"], answer: 0 },
  { id: 56, type: "tf", text: "In Tinkercad, you can select multiple shapes at once by dragging a selection box around them, or by shift-clicking each one.", answer: true }
];
